name: Chord Display Package Deploy

on:
  push:
    branches:
      - "master"
    paths:
      - "chords/**"
      - ".github/workflows/deploy-chords-package.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Node setup
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          
      - name: Install API modules
        run: yarn install:chords

      - name: Publish Package
        run: yarn publish:chords
      

