name: Web Deploy

on:
  push:
    branches:
     - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Node setup
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install modules and build
        run: |
          yarn
          yarn build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.magicdidac.com
          username: u529068159.ftp_chords
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          port: 21
